version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pg
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  api:
    build: .
    container_name: simple-api
    environment:
      DATABASE_HOST: db
      DATABASE_USER: appuser
      DATABASE_PASSWORD: strongpassword
      DATABASE_NAME: appdb
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - appnet

volumes:
  pgdata:

networks:
  appnet:
