version: "3.8"

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mailhog-net

  api:
    build: .
    container_name: mailhog-api
    ports:
      - "3001:3000"
    depends_on:
      - mailhog
    environment:
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    networks:
      - mailhog-net

networks:
  mailhog-net: {}
